[package]
name = "colorname"
version = "0.1.0"
edition = "2024"
description = "A simple CLI tool to get color data based on color names in multiple languages from various lists."
license = "MIT"
readme = "README.md"
keywords = ["cli", "colors"]
categories = ["command-line-utilities"]
homepage = "https://github.com/rivea0/colorname"
repository = "https://github.com/rivea0/colorname"

[dependencies]
anyhow = "1.0"
clap = { version = "4.6.1", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
csv = "1.4.0"
indexmap = { version = "2.14.0", features = ["serde"] }
comfy-table = "8.0.0"

[build-dependencies]
anyhow = "1"

[dev-dependencies]
tempfile = "3.27.0"
assert_cmd = "2.2.2"
predicates = "3.1.4"
